//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avn.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avn.Services.Resources.BusinessMessage", typeof(BusinessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is deactive.
        /// </summary>
        public static string AccountIsDeActive {
            get {
                return ResourceManager.GetString("AccountIsDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Is Lockout.
        /// </summary>
        public static string AccountIsLockout {
            get {
                return ResourceManager.GetString("AccountIsLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProjectOperationFail.
        /// </summary>
        public static string AddProjectOperationFail {
            get {
                return ResourceManager.GetString("AddProjectOperationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DouplicateEmail.
        /// </summary>
        public static string DouplicateEmail {
            get {
                return ResourceManager.GetString("DouplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropHasNoImage.
        /// </summary>
        public static string DropHasNoImage {
            get {
                return ResourceManager.GetString("DropHasNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropIsForTest.
        /// </summary>
        public static string DropIsForTest {
            get {
                return ResourceManager.GetString("DropIsForTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropNotConfirmed.
        /// </summary>
        public static string DropNotConfirmed {
            get {
                return ResourceManager.GetString("DropNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidFileContent.
        /// </summary>
        public static string InvalidFileContent {
            get {
                return ResourceManager.GetString("InvalidFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidNetwork.
        /// </summary>
        public static string InvalidNetwork {
            get {
                return ResourceManager.GetString("InvalidNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Prameter!.
        /// </summary>
        public static string InvalidPrameter {
            get {
                return ResourceManager.GetString("InvalidPrameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSubscriptionModel.
        /// </summary>
        public static string InvalidSubscriptionModel {
            get {
                return ResourceManager.GetString("InvalidSubscriptionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidUser.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username Or Password!.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordNotFound.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!  Server Error..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Transaction is failed! Please try again later..
        /// </summary>
        public static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateProjectOperationFail.
        /// </summary>
        public static string UpdateProjectOperationFail {
            get {
                return ResourceManager.GetString("UpdateProjectOperationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIsActive.
        /// </summary>
        public static string UserIsActive {
            get {
                return ResourceManager.GetString("UserIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
